title: Product
type: object
properties:
  id:
    type: integer
    example: 77
    description: The product id
  name:
    type: string
    example: Rocinante
    description: Product name
  description:
    type: string
    example: The Rocinante (Roci) is a Corvette-class frigate with multiple roles, such as torpedo bomber and boarding party insertion. Originally commissioned as the MCRN Tachi, the ship was stationed onboard the MCRN Battleship Donnager.
    description: Product description
  vendor:
    type: string
    example: MCRN
    description: Product vendor
  price:
    type: number
    example: 3500000.5
    description: Product price (in the specified currency)
  currency:
    type: string
    example: CNY
    description: Currency
  main_category:
    $ref: ./Category.yaml
  images:
    type: array
    items:
      $ref: ./Image.yaml
