openapi: 3.0.0

info:
  title: Redis Product Catalogue Service
  description: |
    A simple REST API providing a way to manage and browse products

    # Auth
    To be implemented

    # Errors
    All errors are returned in the following format:

    ```json
    {
        "title": "Error title",
        "description": "Error description",
    }
    ```

    # Pagination


    ```json
    {
        "title": "Error title",
        "description": "Error description",
    }
    ```

    Endpoint specific errors are defined in their appropriate endpoint
  x-logo:
    url: "https://i.ibb.co/VS6VZLV/logo.png"
    altText: Petstore logo

servers:
  - description: Staging
    url: http://ec2-3-122-233-203.eu-central-1.compute.amazonaws.com/api

tags:
  - name: Products
  - name: Images
x-tagGroups:
  - name: Resources
    tags:
      - Products
      - Images

paths:
  /products:
    $ref: ./paths/Products.yaml
  /products/{id}:
    $ref: ./paths/Product.yaml
  /products/{id}/images:
    $ref: ./paths/Images.yaml
  /images/{id}:
    $ref: ./paths/Image.yaml

components:
