openapi: 3.0.0

info:
  title: Redis Product Catalogue Service
  description: |
    A simple REST API providing a way to manage and browse products

    # Auth
    To be implemented

    # Errors
    All errors are returned in the following format:

    ```json
    {
        "title": "Error title",
        "description": "Error description",
    }
    ```

    Endpoint specific errors are defined in their appropriate endpoint


servers:
  - description: Staging
    url: api/

tags:
  - name: Products
  - name: Images

paths:
  /products:
    $ref: ./paths/Products.yaml
  /products/{id}:
    $ref: ./paths/Product.yaml
  /products/{id}/images:
    $ref: ./paths/Images.yaml
  /images/{id}:
    $ref: ./paths/Image.yaml

components:
